rawList = [
 {
   "question": "En un cine había sesenta y cuatro personas y han entrado diecisiete más. ¿Cuántas personas hay ahora en el cine?",
   "existImg": false,
   "image": "default",
   "A": "Ochenta y uno",
   "B": "Setenta y uno",
   "C": "Cuarenta y siete",
   "D": "Cincuenta y siete",
   "answer": 1,
   "level": 5,
   "grade": 2
 },
 {
   "question": "Un dibujante hace 9 dibujos cada día. ¿Cuántos dibujos hace en 7 días?",
   "existImg": false,
   "image": "default",
   "A": "49",
   "B": "42",
   "C": "56",
   "D": "63",
   "answer": 4,
   "level": 5,
   "grade": 2
 },
 {
   "question": "Un cartero tenía que repartir 798 cartas y lleva repartidas 390. ¿Cuántas cartas le faltan por repartir?",
   "existImg": false,
   "image": "default",
   "A": "Menos de la mitad",
   "B": "Más de la mitad",
   "C": "La mitad",
   "D": "Ya terminó",
   "answer": 2,
   "level": 5,
   "grade": 2
 },
 {
   "question": "En una colmena en la que viven 168 abejas, 32 se quedaron a trabajar ahi. El resto ha salido a buscar polen. ¿Cuántas abejas más trabajan recolectando polen que en la colmena?",
   "existImg": false,
   "image": "default",
   "A": "32",
   "B": "136",
   "C": "104",
   "D": "168",
   "answer": 3,
   "level": 5,
   "grade": 2
 },
 {
   "question": "Radio Pasillo decide poner 4 rumbitas por hora, el número de rumbitas que emitirá Radio Pasillo, entre las 9 de la noche del martes hasta las 5 de la mañana del miércoles de la misma semana es",
   "existImg": false,
   "image": "default",
   "A": "50",
   "B": "54",
   "C": "32",
   "D": "96",
   "answer": 3,
   "level": 5,
   "grade": 2
 },
 {
   "question": "¿Cuántos números diferentes de tres cifras se pueden construir usando los dígitos 0, 1 y 2, sin empezar con 0 ?",
   "existImg": false,
   "image": "default",
   "A": "6",
   "B": "9",
   "C": "12",
   "D": "4",
   "answer": 4,
   "level": 5,
   "grade": 2
 },
 {
   "question": "Aquí están en desorden las fechas de los cumpleaños de Alfonso, Carlos, Claudia y Sofía: 24 de Febrero, 2 de Marzo, 5 de Mayo y 24 de Marzo. Carlos y Alfonso nacieron el mismo mes; Carlos y Sofía cumplen el mismo día pero en distinto mes. ¿Quién nació el 5 de Mayo?",
   "existImg": false,
   "image": "default",
   "A": "Carlos",
   "B": "Sofía",
   "C": "Claudia",
   "D": "Alfonso",
   "answer": 3,
   "level": 5,
   "grade": 2
 },
 {
   "question": "Mariana lee 40 páginas de un libro en un día, al día siguiente lee 12 páginas más que el primer día. ¿Cuántas páginas leyó en los dos días? ",
   "existImg": false,
   "image": "default",
   "A": "40",
   "B": "92",
   "C": "12",
   "D": "52",
   "answer": 2,
   "level": 5,
   "grade": 2
 },
 {
   "question": "Un señor empieza a trabajar a las 9 de la mañana. Tarda 10 minutos en bañarse, 20 minutos en desayunar, 10 minutos en vestirse y 20 minutos en trasladarse a su trabajo. ¿A qué hora se debe de levantar para llegar a tiempo a su trabajo?",
   "existImg": false,
   "image": "default",
   "A": "9 : 00",
   "B": "8 : 30",
   "C": "8 : 00",
   "D": "7 : 30",
   "answer": 3,
   "level": 5,
   "grade": 2
 },
 {
   "question": "En el patio hay 2 gallinas y 2 conejos jugando. ¿Cuántas patas de animales hay en total en el patio?",
   "existImg": false,
   "image": "default",
   "A": "12",
   "B": "10",
   "C": "8",
   "D": "4",
   "answer": 1,
   "level": 5,
   "grade": 1
 },
 {
   "question": "Hoy es Jueves. El cumpleaños de Eagle fue hace 4 días. ¿En qué día de la semana fue el cumpleaños de Eagle?",
   "existImg": false,
   "image": "default",
   "A": "Domingo",
   "B": "Lunes",
   "C": "Martes",
   "D": "Miércoles",
   "answer": 1,
   "level": 5,
   "grade": 1
 },
 {
   "question": "Las caras opuestas de un dado suman 7, ¿cuál es la cara opuesta al tres?",
   "existImg": true,
   "image": "PrimerGrado_20",
   "A": "1",
   "B": "4",
   "C": "5",
   "D": "No se sabe",
   "answer": 2,
   "level": 5,
   "grade": 1
 },
 {
   "question": "Estrella resolvió las siguientes dos operaciones y tapó algunos números con figuras. Cada figura, representa un número diferente. ¿Qué número está abajo de la figura de corazón?",
   "existImg": true,
   "image": "PrimerGrado_21",
   "A": "10",
   "B": "17",
   "C": "19",
   "D": "20",
   "answer": 3,
   "level": 5,
   "grade": 1
 },
 {
   "question": "El siguiente cuadrado está dividido en 16 cuadritos. Cada cuadrito se debe colorear con alguno de estos 4 colores: amarillo, azul, rojo o verde. No se puede repetir el color en la misma columna ni en la misma fila. ¿Qué color corresponde al cuadradito de arriba a la derecha?",
   "existImg": true,
   "image": "PrimerGrado_22",
   "A": "Amarillo",
   "B": "Azul",
   "C": "Rojo",
   "D": "Verde",
   "answer": 2,
   "level": 5,
   "grade": 1
 },
 {
   "question": "Mi mamá cuelga la ropa afuera, ella quiere usar el menor número de pinzas posible para colgar la ropa. Para 3 toallas ella necesita 4 pinzas, como se muestra en la imagen. ¿Cuántas pinzas se necesitarán para nueve toallas?",
   "existImg": true,
   "image": "PrimerGrado_28",
   "A": "9",
   "B": "10",
   "C": "12",
   "D": "16",
   "answer": 2,
   "level": 5,
   "grade": 1
 },
 {
   "question": "¿Cuántas letras tienen en común las palabras estrella y justicia?",
   "existImg": false,
   "image": "default",
   "A": "1",
   "B": "2",
   "C": "3",
   "D": "4",
   "answer": 3,
   "level": 5,
   "grade": 1
 },
 {
   "question": "Julio escribió todos los números del 1 al 60. ¿Cuántas veces usó el dígito 5?",
   "existImg": false,
   "image": "default",
   "A": "15",
   "B": "16",
   "C": "6",
   "D": "7",
   "answer": 2,
   "level": 5,
   "grade": 1
 },
 {
   "question": "Dentro de una caja hay dos cajas, cada una de esas dos cajas contiene tres cajas. ¿Cuántas cajas hay en total?",
   "existImg": false,
   "image": "default",
   "A": "9",
   "B": "10",
   "C": "12",
   "D": "13",
   "answer": 1,
   "level": 5,
   "grade": 1
 },
 {
   "question": "Hoy es 18 febrero de 2010 y tengo 7 años. ¿Cuántos años tendré el 18 de febrero de 2020?",
   "existImg": false,
   "image": "default",
   "A": "17 años",
   "B": "16 años",
   "C": "13 años",
   "D": "12 años",
   "answer": 1,
   "level": 5,
   "grade": 1
 },
 {
   "question": "Al dividir 4.5 entre 0.5 se obtiene:",
   "existImg": false,
   "image": "default",
   "A": "0 . 9",
   "B": "9",
   "C": "0 . 5",
   "D": "0 . 09",
   "answer": 2,
   "level": 5,
   "grade": 4
 },
 {
   "question": "Un apicultor tiene 65 colmenas con 12 panales cada una. Si de cada panal obtiene medio kilo de miel, ¿cuántos kilos obtendrá en cada cosecha? ",
   "existImg": false,
   "image": "default",
   "A": "390 kg",
   "B": "298 kg",
   "C": "65 kg",
   "D": "120 kg",
   "answer": 1,
   "level": 5,
   "grade": 4
 },
 {
   "question": "Un reloj digital marca 2:54, un minuto después hay un cambio de dígito. ¿Qué hora marcará después de 16 cambios de dígitos?",
   "existImg": false,
   "image": "default",
   "A": "3 : 01",
   "B": "3 : 10",
   "C": "3 : 08",
   "D": "4 : 01",
   "answer": 3,
   "level": 5,
   "grade": 4
 },
 {
   "question": "Si hay 16 jugadores de ping pong inscritos en un torneo, en el cual el que pierde sale del torneo, ¿cuántos juegos se juegan hasta encontrar al campeón?",
   "existImg": false,
   "image": "default",
   "A": "8",
   "B": "12",
   "C": "15",
   "D": "16",
   "answer": 3,
   "level": 5,
   "grade": 4
 },
 {
   "question": "El 2 de septiembre de 2018 cae en domingo. ¿Qué día de la semana cae el 25 de septiembre?",
   "existImg": false,
   "image": "default",
   "A": "Jueves",
   "B": "Martes",
   "C": "Sábado",
   "D": "Miércoles",
   "answer": 2,
   "level": 5,
   "grade": 4
 },
 {
   "question": "En una tómbola, hay 10 boletos etiquetados de 0 a 9. Luna y Estrella sacan cada una, tres de los boletos de la tómbola y suman los números de sus boletos. ¿Cuál es la mayor diferencia que pueden tener las sumas de Luna y Estrella? ",
   "existImg": false,
   "image": "default",
   "A": "1",
   "B": "12",
   "C": "18",
   "D": "21",
   "answer": 4,
   "level": 5,
   "grade": 4
 },
 {
   "question": "En el salón de clase se quieren formar equipos de juego que estén formados por una niña y un niño. Hoy asistieron 17 niños y 29 niñas. ¿Cuántos equipos diferentes se pueden formar?",
   "existImg": false,
   "image": "default",
   "A": "46",
   "B": "473",
   "C": "493",
   "D": "943",
   "answer": 3,
   "level": 5,
   "grade": 4
 },
 {
   "question": "Theffanie cocinó 45 cupcakes para sus amigas. Ella utilizó fresas y chispas de chocolate. Primero decoró 27 cupcakes con fresas y luego 36 con chispas de chocolate. Ningún cupcake quedó sin decorar. ¿Cuántos cupcakes tenían tanto fresas como chispas de chocolate? ",
   "existImg": false,
   "image": "default",
   "A": "18",
   "B": "27",
   "C": "36",
   "D": "9",
   "answer": 1,
   "level": 5,
   "grade": 4
 },
 {
   "question": "La figura que se muestra se puede cubrir con cuatro partes iguales como las que aparecen a continuación. Indica cuál de las siguientes no la cubre.",
   "existImg": true,
   "image": "CuartoGrado_19",
   "A": "",
   "B": "",
   "C": "",
   "D": "",
   "answer": 3,
   "level": 5,
   "grade": 4
 },
 {
   "question": "Al hacer una cuenta en la calculadora Sofía se equivocó y en vez de sumar, restó 26. Para obtener el resultado correcto con una sola operación debe:",
   "existImg": false,
   "image": "default",
   "A": "Sumar 26",
   "B": "Restar 26",
   "C": "Sumar 52",
   "D": "Restar 56",
   "answer": 3,
   "level": 5,
   "grade": 4
 },
 {
   "question": "A la siguiente multiplicación le falta un dígito. ¿Con qué número se debe reemplazar la letra A?",
   "existImg": true,
   "image": "CuartoGrado_21",
   "A": "5",
   "B": "7",
   "C": "9",
   "D": "6",
   "answer": 1,
   "level": 5,
   "grade": 4
 },
 {
   "question": "En la figura se ve una construcción hecha con cubos, desde la izquierda y de frente, respectivamente. ¿Cuál es el máximo número de cubos usados?",
   "existImg": true,
   "image": "CuartoGrado_22",
   "A": "14",
   "B": "15",
   "C": "16",
   "D": "17",
   "answer": 3,
   "level": 5,
   "grade": 4
 },
 {
   "question": "¿Cuántos cuadrados blancos se deben pintar de color verde para que haya exactamente el doble de cuadrados blancos que verdes?",
   "existImg": true,
   "image": "CuartoGrado_23",
   "A": "1",
   "B": "2",
   "C": "3",
   "D": "4",
   "answer": 3,
   "level": 5,
   "grade": 4
 },
 {
   "question": "En la biblioteca cobran $ 3.00 por entregar un libro un día tarde y $ 1.00 por cada día adicional a ese. Arthurius pagó $ 10.00 por entregar un libro con retraso. ¿Cuántos días se retrasó?",
   "existImg": false,
   "image": "default",
   "A": "6",
   "B": "7",
   "C": "8",
   "D": "9",
   "answer": 3,
   "level": 5,
   "grade": 4
 },
 {
   "question": "Julia cortó una hoja de papel en 10 pedazos. Luego, tomó uno de los pedazos y la dividió en otros 10. Más tarde, volvió a repetir el proceso dos veces. ¿Cuántos pedazos de papel tiene al final?",
   "existImg": false,
   "image": "default",
   "A": "27",
   "B": "30",
   "C": "37",
   "D": "40",
   "answer": 3,
   "level": 5,
   "grade": 4
 },
 {
   "question": "Considera la secuencia (2,1), (4,4), (6,9), (8,16). ¿Cuál es la siguiente pareja de números?",
   "existImg": false,
   "image": "default",
   "A": "(16,16)",
   "B": "(10,25)",
   "C": "(12,18)",
   "D": "(10,27)",
   "answer": 2,
   "level": 5,
   "grade": 6
 },
 {
   "question": "Una pirámide de números está hecha por bloques tal que cada bloque contiene una fracción que es la suma de las dos fracciones que están en los bloques de abajo. ¿Qué número debe de ir en el bloque azul?",
   "existImg": true,
   "image": "SextoGrado_18",
   "A": "43435",
   "B": "43256",
   "C": "43441",
   "D": "43191",
   "answer": 4,
   "level": 5,
   "grade": 6
 },
 {
   "question": "¿Cuántos números del 1 al 100 son divisibles por 4 o por 9?",
   "existImg": false,
   "image": "default",
   "A": "34",
   "B": "30",
   "C": "24",
   "D": "10",
   "answer": 1,
   "level": 5,
   "grade": 6
 },
 {
   "question": "¿De cuántas maneras diferentes se pueden sentar en una banca Nao, Oof y Paz, si Oof y Paz se quieren sentar juntos?",
   "existImg": false,
   "image": "default",
   "A": "12",
   "B": "8",
   "C": "4",
   "D": "2",
   "answer": 3,
   "level": 5,
   "grade": 6
 },
 {
   "question": "En una banda compuesta por un baterista, un guitarrista, un bajista y un saxofonista, el baterista toca en lapsos de 8 tiempos, el guitarrista en 12 tiempos, el bajista en 6 tiempos y el saxofonista en 16 tiempos. Si todos empiezan al mismo tiempo, ¿en cuántos tiempos sus periodos volverán a coincidir?",
   "existImg": false,
   "image": "default",
   "A": "48",
   "B": "32",
   "C": "24",
   "D": "18",
   "answer": 1,
   "level": 5,
   "grade": 6
 },
 {
   "question": "La suma de los divisores de 124 es",
   "existImg": false,
   "image": "default",
   "A": "124",
   "B": "99",
   "C": "189",
   "D": "224",
   "answer": 4,
   "level": 5,
   "grade": 6
 },
 {
   "question": "Eagle y Tomiko pueden podar el jardín en 40 minutos si trabajan juntos. Si Tomiko poda el doble de rápido que Eagle. ¿Cuántos minutos tardará Eagle en podar el jardín él solo?",
   "existImg": false,
   "image": "default",
   "A": "20",
   "B": "120",
   "C": "80",
   "D": "40",
   "answer": 2,
   "level": 5,
   "grade": 6
 },
 {
   "question": "¿Cuántas palabras diferentes (con o sin sentido) se pueden formar con las letras A,M,A,R,A?",
   "existImg": false,
   "image": "default",
   "A": "12",
   "B": "16",
   "C": "20",
   "D": "24",
   "answer": 3,
   "level": 5,
   "grade": 6
 },
 {
   "question": "Determina la superficie exterior considerando también la de abajo del siguiente volumen formado por 4 cubos con arista de 1 cm.",
   "existImg": true,
   "image": "SextoGrado_19",
   "A": "4",
   "B": "18",
   "C": "24",
   "D": "36",
   "answer": 2,
   "level": 5,
   "grade": 6
 },
 {
   "question": "El promedio de tres exámenes es 95. Y de los siguientes dos exámenes es de 90. ¿Cuál es el promedio de los 5 exámenes?",
   "existImg": false,
   "image": "default",
   "A": "92.5",
   "B": "93",
   "C": "93.5",
   "D": "94",
   "answer": 2,
   "level": 5,
   "grade": 6
 },
 {
   "question": "La cifra de las unidades del siguiente producto es",
   "existImg": true,
   "image": "SextoGrado_20",
   "A": "1",
   "B": "8",
   "C": "7",
   "D": "5",
   "answer": 3,
   "level": 5,
   "grade": 6
 },
 {
   "question": "En una escuela el 68% de los alumnos tiene celular. De ese 68% sólo el 30% tiene un celular marca Yogocel. Si en la escuela hay 2000 alumnos, ¿cuántos alumnos tienen un Yogocel?",
   "existImg": false,
   "image": "default",
   "A": "408",
   "B": "600",
   "C": "1360",
   "D": "1400",
   "answer": 1,
   "level": 5,
   "grade": 6
 },
 {
   "question": "Un conejo comió 100 hojas de lechuga en un periodo de 5 días. Cada día, comió 6 hojas de lechuga más que el día anterior. ¿Cuántas hojas de lechuga comió el primer día?",
   "existImg": false,
   "image": "default",
   "A": "4",
   "B": "8",
   "C": "12",
   "D": "18",
   "answer": 2,
   "level": 5,
   "grade": 6
 },
 {
   "question": "Las caras opuestas de un cubo tienen el mismo color. ¿Cuál de estos patrones puede ser el del cubo?",
   "existImg": true,
   "image": "SextoGrado_21",
   "A": "A",
   "B": "B",
   "C": "C",
   "D": "D",
   "answer": 4,
   "level": 5,
   "grade": 6
 },
 {
   "question": "En un viaje de 5h 15 min, Paco ve una sola película de 2h 25 min. El resto del tiempo se durmió. ¿Cuánto tiempo durmió Paco?",
   "existImg": false,
   "image": "default",
   "A": "145 min",
   "B": "2h 50 min",
   "C": "2h 15 min",
   "D": "2h 35 min",
   "answer": 2,
   "level": 5,
   "grade": 6
 },
 {
   "question": "¿Cuántos días hay en ocho semanas más ocho días?",
   "existImg": false,
   "image": "default",
   "A": "63",
   "B": "64",
   "C": "65",
   "D": "66",
   "answer": 2,
   "level": 5,
   "grade": 3
 },
 {
   "question": "De los siguientes productos, ¿cuál tiene la cifra de unidades más pequeña?",
   "existImg": false,
   "image": "default",
   "A": "7 X 8 X 9 ",
   "B": "6 X 7 X 8",
   "C": "4 X 6 X 7",
   "D": "5 X 6 X 7",
   "answer": 4,
   "level": 5,
   "grade": 3
 },
 {
   "question": "En una reunión, todas las personas se saludaron de mano y en total hubo 28 saludos. ¿Cuántas personas había en la reunión?",
   "existImg": false,
   "image": "default",
   "A": "6",
   "B": "7",
   "C": "8",
   "D": "9",
   "answer": 3,
   "level": 5,
   "grade": 3
 },
 {
   "question": "¿Cuántos números impares hay entre 30 y 50?",
   "existImg": false,
   "image": "default",
   "A": "10",
   "B": "12",
   "C": "13",
   "D": "14",
   "answer": 1,
   "level": 5,
   "grade": 3
 },
 {
   "question": "Juan cuenta en reversa, de 6 en 6, a partir del sesenta (60, 54, ...) El número que no dice es",
   "existImg": false,
   "image": "default",
   "A": "48",
   "B": "30",
   "C": "26",
   "D": "18",
   "answer": 3,
   "level": 5,
   "grade": 3
 },
 {
   "question": "¿Cuántos segundos son dos minutos y medio?",
   "existImg": false,
   "image": "default",
   "A": "150",
   "B": "160",
   "C": "180",
   "D": "120 .5",
   "answer": 1,
   "level": 5,
   "grade": 3
 },
 {
   "question": "¿Cuántos múltiplos de 7 hay desde el 7 hasta el 77, incluyéndolos?",
   "existImg": false,
   "image": "default",
   "A": "7",
   "B": "10",
   "C": "11",
   "D": "70",
   "answer": 3,
   "level": 5,
   "grade": 3
 },
 {
   "question": "Una contestadora tiene espacio para grabar 10 minutos. El número de mensajes de 20 segundos que puede grabar es",
   "existImg": false,
   "image": "default",
   "A": "50",
   "B": "60",
   "C": "70",
   "D": "30",
   "answer": 4,
   "level": 5,
   "grade": 3
 },
 {
   "question": "La cifra de las decenas que se obtiene al restar 428 y 348 es",
   "existImg": false,
   "image": "default",
   "A": "0",
   "B": "1",
   "C": "9",
   "D": "8",
   "answer": 4,
   "level": 5,
   "grade": 3
 },
 {
   "question": "En el siguiente cuadrado, si F es el punto medio de AB, ¿qué parte del total representa la parte coloreada? ",
   "existImg": true,
   "image": "TercerGrado_10",
   "A": "43191",
   "B": "43132",
   "C": "43160",
   "D": "43193",
   "answer": 1,
   "level": 5,
   "grade": 3
 },
 {
   "question": "Si sumamos un cuarto de hora, más media hora, más una hora, ¿cuántos minutos hay en total?",
   "existImg": false,
   "image": "default",
   "A": "100",
   "B": "110",
   "C": "115",
   "D": "105",
   "answer": 4,
   "level": 5,
   "grade": 3
 },
 {
   "question": "El doble de un número menos el número es 7, el número es",
   "existImg": false,
   "image": "default",
   "A": "14",
   "B": "10",
   "C": "7",
   "D": "21",
   "answer": 3,
   "level": 5,
   "grade": 3
 },
 {
   "question": "Si cambiamos el orden de los dígitos del número 2018, ¿qué número, múltiplo de 10, es el mayor que se puede formar?",
   "existImg": false,
   "image": "default",
   "A": "8012",
   "B": "8021",
   "C": "8120",
   "D": "8210",
   "answer": 4,
   "level": 5,
   "grade": 3
 },
 {
   "question": "Pedro efectúa la operación 72 x 8 y María efectúa la operación 72 / 8. La diferencia entre el resultado de Pedro y el de María es",
   "existImg": false,
   "image": "default",
   "A": "755",
   "B": "567",
   "C": "575",
   "D": "757",
   "answer": 2,
   "level": 5,
   "grade": 3
 },
 {
   "question": "Arthurius observa la secuencia 113, 124, 135, 146 y se pregunta: ¿qué número sigue?",
   "existImg": false,
   "image": "default",
   "A": "156",
   "B": "567",
   "C": "123",
   "D": "111",
   "answer": 2,
   "level": 5,
   "grade": 3
 },
 {
   "question": "Pepe armó la siguiente figura con 4 fichas cuadradas iguales y 3 fichas rectangulares iguales. Tres fichas cuadradas forman una rectangular. La ficha rectangular tiene un perímetro de 56 cm. ¿Cuál es el perímetro de la figura?",
   "existImg": true,
   "image": "QuintoGrado_17",
   "A": "196 cm",
   "B": "217 cm",
   "C": "231 cm",
   "D": "224 cm",
   "answer": 1,
   "level": 5,
   "grade": 5
 },
 {
   "question": "Para producir 5 kg de papel se necesitan 14.18 kg de madera. ¿Cuántos kg de madera se necesitan para producir 5 toneladas de papel?",
   "existImg": false,
   "image": "default",
   "A": "7090 kg",
   "B": "70900 kg",
   "C": "14180 kg",
   "D": "1418 kg",
   "answer": 3,
   "level": 5,
   "grade": 5
 },
 {
   "question": "La agencia \"Viaje Feliz\" cobra $ 2160 por 135 personas. Si el número de pasajeros es mayor que 135 cobra las tres cuartas partes del valor del pasaje. Un grupo de más de 135 personas va a ir a la excursión la próxima semana y les cobraron $ 2160. ¿Cuántas personas más van a ir?",
   "existImg": false,
   "image": "default",
   "A": "105",
   "B": "81",
   "C": "9",
   "D": "45",
   "answer": 4,
   "level": 5,
   "grade": 5
 },
 {
   "question": "En la siguiente figura BD es perpendicular a AE, BD = 2AC, DE = 2BD, y el área del triángulo isósceles ABC es 36 cm<sup>2</sup> . ¿Cuál es el área del triángulo ABE?",
   "existImg": true,
   "image": "QuintoGrado_18",
   "A": "180 cm2",
   "B": "162 cm2",
   "C": "306 cm2",
   "D": "153 cm2",
   "answer": 2,
   "level": 5,
   "grade": 5
 },
 {
   "question": "Lolis tiene 4 amigos: Aldo, Beto, Carlos y Daniel, y 4 amigas: Elia, Fernanda, Gaby e Hilda, de los cuales quiere invitar a 3 amigos y 2 amigas a su fiesta. ¿De cuántas formas puede hacer sus invitaciones?",
   "existImg": false,
   "image": "default",
   "A": "36",
   "B": "12",
   "C": "16",
   "D": "24",
   "answer": 4,
   "level": 5,
   "grade": 5
 },
 {
   "question": "Un comerciante compró 100 bolsas de papas por $ 600.00 . Vendió <div class='fraction'><span class='numerador'>3</span><span class='barfrac'>/</span><span class='denominador'>5</span></div> de las bolsas a $ 8.00 pesos cada una. Quiere obtener una ganancia total de $ 240 por vender todas las bolsas. ¿En qué precio debe vender las bolsas que le quedan?",
   "existImg": false,
   "image": "default",
   "A": "$ 7.00",
   "B": "$ 8.00",
   "C": "$ 9.00",
   "D": "$ 10.00",
   "answer": 3,
   "level": 5,
   "grade": 5
 },
 {
   "question": "Pepe tiene 3 cajas: una blanca, una verde y una roja, y en ellas quiere guardar 18 canicas iguales. ¿De cuántas formas puede guardarlas si no quiere cajas vacías y en cada una debe haber un número de canicas múltiplo de 3?",
   "existImg": false,
   "image": "default",
   "A": "28",
   "B": "19",
   "C": "10",
   "D": "7",
   "answer": 3,
   "level": 5,
   "grade": 5
 },
 {
   "question": "La figura está formada por 2 cuadrados iguales de lado L y un triángulo isósceles de altura h=  <div class='fraction'><span class='numerador'>1</span><span class='barfrac'>/</span><span class='denominador'>2</span></div> L. El área del triángulo es de 2 cm<sup>2</sup>. ¿Cuál es el área de la figura?",
   "existImg": true,
   "image": "QuintoGrado_19",
   "A": "8 cm2",
   "B": "16 cm2",
   "C": "10 cm2",
   "D": "18 cm2",
   "answer": 4,
   "level": 5,
   "grade": 5
 },
 {
   "question": "Un comerciante tenía 6 piezas de tela. Vendió cierta cantidad de esta a un cliente, el doble a otro y le quedó una pieza. Las ventas las hizo por piezas enteras. Las longitudes de las piezas eran, en metros, de 15, 16, 18, 19, 20 y 31. La pieza que le quedó fue la de: ",
   "existImg": false,
   "image": "default",
   "A": "15 m",
   "B": "18 m",
   "C": "20 m",
   "D": "31 m",
   "answer": 3,
   "level": 5,
   "grade": 5
 },
 {
   "question": "Juan tiene un librero con un número impar de libros. Si los empaca en cajas de 3, de 5, o de 9 libros, siempre le sobra un libro. ¿Cuántos libros tiene Juan si son menos de 100?",
   "existImg": false,
   "image": "default",
   "A": "47",
   "B": "64",
   "C": "73",
   "D": "91",
   "answer": 4,
   "level": 5,
   "grade": 5
 },
 {
   "question": "En el siguiente cuadrado los números de los óvalos son el resultado de la suma de los números que aparecen en los círculos adyacentes. La suma de los números de los tres círculos que están vacíos es",
   "existImg": true,
   "image": "QuintoGrado_27",
   "A": "19",
   "B": "21",
   "C": "17",
   "D": "29",
   "answer": 2,
   "level": 5,
   "grade": 5
 },
 {
   "question": "En un avión, las filas están numeradas del 1 al 25, pero no hay fila 13. La fila 15 tiene solo 4 asientos para pasajeros; las demás filas tienen 6 asientos para pasajeros. ¿Cuántos asientos de pasajeros hay en el avión?",
   "existImg": false,
   "image": "default",
   "A": "120",
   "B": "138",
   "C": "142",
   "D": "144",
   "answer": 3,
   "level": 5,
   "grade": 5
 },
 {
   "question": "Lucy quiere acomodar 12 números en un círculo de tal manera que cualquier par de números vecinos siempre difieran por 1 o 2. De los siguientes pares de números, ¿cuáles tienen que ser vecinos?",
   "existImg": true,
   "image": "QuintoGrado_20",
   "A": "5 y 6",
   "B": "9 y 10",
   "C": "6 y 7",
   "D": "8 y 10",
   "answer": 4,
   "level": 5,
   "grade": 5
 },
 {
   "question": "Si consideras todos los números de 4 dígitos que se pueden formar con los dígitos de 2018, por ejemplo, 1028 o 2180, y luego los escribes en orden creciente, ¿cuál es la diferencia entre los dos números que quedan a cada lado de 2018?",
   "existImg": false,
   "image": "default",
   "A": "261",
   "B": "1026",
   "C": "900",
   "D": "90",
   "answer": 1,
   "level": 5,
   "grade": 5
 },
 {
   "question": "El lado del cuadrado ABCD mide 5 cm. El punto P está a una distancia de 5 cm del punto A y a una distancia de 1 cm del lado BC. ¿Cuál es el área del triángulo APD?",
   "existImg": true,
   "image": "QuintoGrado_21",
   "A": "8 cm2",
   "B": "10 cm2",
   "C": "25 cm2",
   "D": "15 cm2",
   "answer": 2,
   "level": 5,
   "grade": 5
 }
]